name: GitHub Pages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: build
      run: |
        yarn --frozen-lockfile
        yarn build
      env:
        REACT_APP_UPDOWN_API_KEY: ${{ secrets.UPDOWN_API_KEY }}
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.2.5
      with:
        build_dir: build
        fqdn: status.alugha.com
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
